#!/bin/bash
sudo yum install -y aws-cli
cd /home/ec2-user/
aws s3 cp s3://aws-codedeploy-ap-south-1/latest/codedeploy-agent.noarch.rpm . --region ap-south-1
sudo yum -y install codedeploy-agent.noarch.rpm
